### PR TITLE
fix missing GFT lots in exported source data

### LINKED ISSUE #815: lots missing from GFT source data exports
## problem

For many datasets we:
1. get points (raw)
2. replace with a lot polygons if one intersects (intermediate)
3. buffer the lots and remaining points (buffered)

For these datasets we export the point, lot, and buffered geometries (e.g. CATs permits, NYC Historic Buildings) so that they can been seen in the GFT app.

GIS noticed that, although the buffers are correct, some `source_xxx_lots` tables are missing lots.

### PR DESCRIPTION
**Pull request by damonmcc**
resolves #815 

successful build [here](https://github.com/NYCPlanning/data-engineering/actions/runs/8913860231). all builds on this branch [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/build.yml?query=branch%3Adm-gft-source-geometry)

I found which models to change by searching for all models in `/product/sources` that select records `WHERE ST_GEOMETRYTYPE(raw_geom) = 'ST_MultiPolygon'` and changing the model they select from.

See [last commit message](https://github.com/NYCPlanning/data-engineering/pull/823/commits) for explanation of the substantial changes to `int_buffers__lpc_landmarks`. GIS is ok with (and actually likes) not seeing source points when lots where they were joined to lots.

### before
Screenshot 2024-05-01 at 12 39 44 PM

### after
Screenshot 2024-05-01 at 12 40 10 PM

### CODE REVIEW

File: products/green_fast_track/models/intermediate/buffers/int_buffers__all.sql [hunk 1]
```diff
@@ -46,6 +46,7 @@ WITH all_buffers AS (
         ref('int_buffers__lpc_landmarks'),
         ref('stg__nysshpo_archaeological_buffer_areas')
     ],
+    include=["variable_type", "variable_id", "raw_geom", "buffer"],
```
Comment (fvankrieken) [inline products/green_fast_track/models/intermediate/buffers/int_buffers__all.sql:49]: What does this do?

**Review by fvankrieken — APPROVED** [review]
Is it potentially worth using ST_MULTI on just about every data source, just to make sure we don't have other

File: products/green_fast_track/models/intermediate/buffers/int_buffers__all.sql (hunk 1 above)
Comment (damonmcc) [reply products/green_fast_track/models/intermediate/buffers/int_buffers__all.sql:49]: just noting for later:

didn't know this util creates a column called `_dbt_source_relation` "to indicate the source for each record"!! seems like a cool way to avoid declaring `variable_type` strings in these models and just use the model names to drive queries??

**Comment by damonmcc** [comment]
@fvankrieken 
> Is it potentially worth using ST_MULTI on just about every data source, just to make sure we don't have other

good call, but I didn't wanna go too far since (especially historic) source data seems to be in flux at the moment and we wanna make a pass at standardizing stuff more generally

all good if we roll with this while Jack and I keep an eye out for other issues?

**Review by sf-dcp — APPROVED** [review]
LGTM!

File: products/green_fast_track/models/intermediate/buffers/int_buffers__all.sql (hunk 1 above)
Comment (fvankrieken) [reply products/green_fast_track/models/intermediate/buffers/int_buffers__all.sql:49]: Ooh that's interesting. Love that
