### PR TITLE
Fvk dtm duplicate bbl fix

### LINKED ISSUE #278: ZTL issues arising from duplicate BBLs in DTM
Per discussion with @caseysmithpgh and @jackrosacker 

New logic in #171 updated some rankings of zoning districts by bbl based on aggregation. There are a couple odd edge cases where it seems there are multiple entries for bbls in dtm. Due to the way the aggregation/ranking of zoning districts logic is written, we're getting (extra) duplicate rows for bbls as well as duplicate rankings.

So if bbl 1 appears twice and should be zd1 = R5 and zd2 = Park (zd3, zd4 both empty), what we're seeing is 
| bbl | zd1 | zd2 | zd3 | zd4 | 
| - | - | - | - | - |
| 1 | R5 | R5 | Park | Park |
| 1 | R5 | R5 | Park | Park |
| 1 | R5 | R5 | Park | Park |
| 1 | R5 | R5 | Park | Park |

We **don't** want to remove the duplicate bbls, since that's coming from dtm. However, we do want to remove the extra rows and duplicated zoning districts

Other random notes
- 2050340001 has second district that doesn't seem to be above threshold
- 2028650160

### PR DESCRIPTION
**Pull request by fvankrieken**
Fixes #278.

Essentially, bbls in dof dtm are not necessarily unique. This needed some cleanup in how we're de-duplicating in preprocessing as well as addition of essentially a primary key for the table to actually identify unique rows.

Pluto needs analogous changes, though it's a bit different - data doesn't just come from dtm, and the aggregations use pluto itself as a source. So for applying the same fix to pluto, I simply added a serial pk to the table

### CODE REVIEW

File: products/zoningtaxlots/sql/bbl.sql [hunk 1]
```diff
@@ -1,19 +1,20 @@
...
 )
 SELECT
+    id,
     bbl,
     boro,
     block,
     lot,
-    ST_AREA(ST_MULTI(ST_UNION(geom))::geography) AS area
-FROM dof_dtm
-GROUP BY bbl, boro, block, lot;
```
Comment (fvankrieken) [inline products/zoningtaxlots/sql/bbl.sql:16]: There was already a group by happening [here](https://github.com/NYCPlanning/data-engineering/pull/280/files#diff-3c953c8ca77cda9b1441cdcf641015b5bcd861e4680648f93b04c294a0b9c629R46) so cleaned this up

File: products/zoningtaxlots/sql/preprocessing.sql [hunk 2]
```diff
@@ -25,13 +25,24 @@ RENAME COLUMN wkb_geometry TO geom;
...
+            bbl,
+            COALESCE(boro::text, LEFT(bbl::text, 1)) AS boro,
+            COALESCE(block::text, SUBSTRING(bbl::text, 2, 5)) AS block,
+            COALESCE(lot::text, SUBSTRING(bbl::text, 7, 4)) AS lot,
+            geom
+        FROM dof_dtm
+    )
+
     SELECT
+        ROW_NUMBER() OVER () AS id,
```
Comment (fvankrieken) [inline products/zoningtaxlots/sql/preprocessing.sql:39]: Figure at point of grouping of dtm, need to essentially generate pk since bbl isn't necessarily it.

File: pyproject.toml [hunk 3]
```diff
@@ -7,6 +7,7 @@ exclude_rules = [
     "ambiguous.column_count",
     "references.qualification",
     "structure.unused_cte",
+    "structure.column_order",
```
Comment (fvankrieken) [inline pyproject.toml:10]: sqlfluff. Let me put my columns in the order I want to!

**Comment by fvankrieken** [comment]
Latest ztl build

https://github.com/NYCPlanning/data-engineering/actions/runs/6487086718

**Comment by fvankrieken** [comment]
@caseysmithpgh identified one remaining issue

**Review by alexrichey — DISMISSED** [review]
Great stuff. I _think_ I get the gist of what's happening. I'm curious how many duplicated BBLs we found in the data? (apologies if it's spelled out in the issue, but I missed it)

**Review by damonmcc — APPROVED** [review]

**Comment by fvankrieken** [comment]
Sorry added one more commit - per convo with @caseysmithpgh, it'd be good to have the dataloading job be able to triggerboth ztl build and pluto minor, not just pluto minor

**Comment by fvankrieken** [comment]
> Great stuff. I _think_ I get the gist of what's happening. I'm curious how many duplicated BBLs we found in the data? (apologies if it's spelled out in the issue, but I missed it)

Fairly small case - 17 cases where we have duplicate bbls due to boro/block/lot columns not aligning with bbl in dof_dtm

**Review by alexrichey — APPROVED** [review]
🤘
