### PR TITLE
fix missing geometry column in qc_bbldiffs

### LINKED ISSUE #1052: ZTL: qc_bbldiff.shp missing geometry
qc_bbldiff shapefile downloaded from [here](https://edm-publishing.nyc3.cdn.digitaloceanspaces.com/db-zoningtaxlots/draft/2024-08-01/1/qc_bbldiffs.shp.zip) appears to be missing geometry. The data opens in the attribute table of both Pro and QGIS, but displays no data on the map.

### PR DESCRIPTION
**Pull request by HengJiang0206**
resolves #1052 

Added `geom` column to `int_zoningtaxlots` and `qc_bbldiffs`

Latest Run:  https://github.com/NYCPlanning/data-engineering/actions/runs/10321459114

Screenshot 2024-08-09 at 12 08 51

### CODE REVIEW

File: products/zoningtaxlots/models/intermediate/int__zoningtaxlots.sql [hunk 1]
```diff
@@ -173,6 +175,7 @@ export AS (
         boroughcode::text AS borough_code,
         TRUNC(taxblock::numeric)::text AS "tax_block",
         taxlot::text AS tax_lot,
+        geom::geometry,
```
Comment (fvankrieken) [inline products/zoningtaxlots/models/intermediate/int__zoningtaxlots.sql:178]: Can we add this to _int_models.yml?

File: products/zoningtaxlots/models/product/qaqc/qc_bbldiffs.sql [hunk 2]
```diff
@@ -16,6 +16,7 @@ bbldiffs AS (
         a.tax_block,
         a.tax_lot,
         a.bbl AS bblnew,
+        a.geom,
```
Comment (fvankrieken) [inline products/zoningtaxlots/models/product/qaqc/qc_bbldiffs.sql:19]: Let's put this column last in the select statement - just a bit of a norm we have

File: products/zoningtaxlots/models/intermediate/int__zoningtaxlots.sql (hunk 1 above)
Comment (fvankrieken) [reply products/zoningtaxlots/models/intermediate/int__zoningtaxlots.sql:178]: And also last in the query

File: products/zoningtaxlots/models/intermediate/int__zoningtaxlots.sql [hunk 3]
```diff
@@ -47,6 +47,7 @@ insertion AS (
         a.boro AS boroughcode,
         a.block AS taxblock,
         a.lot AS taxlot,
+        a.geom,
```
Comment (fvankrieken) [inline products/zoningtaxlots/models/intermediate/int__zoningtaxlots.sql:50]: This one can stay where it is - we reorder later

**Review by fvankrieken — APPROVED** [review]
